#!/bin/bash

set -x

ln -s /opt/m51-lighthouse/usr/share/m51-lighthouse.service /etc/systemd/system/m51-lighthouse.service
systemctl daemon-reload
systemctl enable m51-lighthouse
# systemctl restart m51-lighthouse
